// filters
export const TOGGLE_IS_FILTER_VISIBLE = 'TOGGLE_IS_FILTER_VISIBLE';
export const SET_FILTER_DATE_FROM = 'SET_FILTER_DATE_FROM';
export const SET_FILTER_DATE_TO = 'SET_FILTER_DATE_TO';
export const SET_SUMMA_FROM = 'SET_PRICE_FROM';
export const SET_SUMMA_TO = 'SET_PRICE_TO';
export const SET_ORDER_STATE_TO_FILTER = 'SET_ORDER_STATE_TO_FILTER';
export const APPLY_PANEL_FILTERS = 'APPLY_PANEL_FILTERS';

export const TOGGLE_THEME = 'TOGGLE_THEME';
export const TOGGLE_ORDER_SELECT = 'TOGGLE_ORDER_SELECT';
export const GET_ORDER_STATES = 'GET_ORDER_STATES';

// table data
export const GENERATE_RANDOM_TABLE_DATA = 'GENERATE_RANDOM_TABLE_DATA';
export const FILTER_TABLE_DATA_BY_ORDER_NO_OR_PERSON = 'FILTER_TABLE_DATA_BY_ORDER_NO_OR_PERSON';
export const GET_PAGE = 'GET_PAGE';
export const TOGGLE_ROW_CHECKED = 'TOGGLE_ROW_CHECKED';
export const DELETE_SELECTED_TABLE_ROWS = 'DELETE_TABLE_ROWS';

// paginator
export const CHANGE_LEFT_INDEX = 'CHANGE_LEFT_INDEX';
export const CHANGE_RIGHT_INDEX = 'CHANGE_RIGHT_INDEX';
export const CHANGE_ACTIVE_INDEX = 'CHANGE_ACTIVE_INDEX';

// checkbox
export const TOGGLE_CHECKBOX_STATE = 'TOGGLE_CHECKBOX_STATE';
export const TOGGLE_CHECKED_ALL_ROWS = 'SELECT_ALL_ROWS';

// modal window delete
export const TOGGLE_MODAL_WINDOW_DELETE_VISIBLE = 'TOGGLE_MODAL_WINDOW_DELETE_VISIBLE';




