// filters
export const TOGGLE_IS_FILTER_VISIBLE = 'TOGGLE_IS_FILTER_VISIBLE';
export const SET_FILTER_DATE_FROM = 'SET_FILTER_DATE_FROM';
export const SET_FILTER_DATE_TO = 'SET_FILTER_DATE_TO';

export const TOGGLE_THEME = 'TOGGLE_THEME';
export const TOGGLE_ORDER_SELECT = 'TOGGLE_ORDER_SELECT';
export const GET_ORDER_STATES = 'GET_ORDER_STATES';
export const GENERATE_RANDOM_TABLE_DATA = 'GENERATE_RANDOM_TABLE_DATA';
export const FILTER_TABLE_DATA_BY_ORDER_NO_OR_PERSON = 'FILTER_TABLE_DATA_BY_ORDER_NO_OR_PERSON';

